title: Fred Heidrich
description: Master student at Queensland University of Technology
contact:
  location: Brisbane, QLD
  phone: 0432542285
email: fredheidrich@icloud.com
show_downloads: false
github: github.com/fredheidrich
google_analytics:
theme: 
